name: 📦 Script Feed-RSS

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v3

    - name: ⚙️ Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: ⚙️ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir
    - name: ✅ Run Script
      run: |
        python ./src/script.py
    - name: ⚙️ Git Config
      run: |
        git config --global user.email "email@fernandocelmer.com"
        git config --global user.name "FernandoCelmer"
    - name: 📝 Git Process 
      run: |
        git add src/assets/rss-sema-rs.xml
        git commit -m "⚙️ FEATURE - Update XML"
        git push https://github.com/BooPixel/bp-psk-feedrss HEAD origin/master
      continue-on-error: true